services:
  db:
    image: mariadb:10.11@sha256:be981e4113326ada8d6004174dd09eeaefc03094037f811182a52d4f2e737350
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "NTV360-Passbolt-Poc-2026!"
    volumes:
      - database_volume:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  passbolt:
    image: passbolt/passbolt:latest-ce@sha256:af3a620902a098cfd7d6eda987c6ba835422ed2f1c14f92174282255871fa44d
    restart: unless-stopped

    depends_on:
      - db
      - mailpit

    environment:
      APP_FULL_BASE_URL: https://passbolt.ntv360.internal

      DATASOURCES_DEFAULT_HOST: db
      DATASOURCES_DEFAULT_USERNAME: passbolt
      DATASOURCES_DEFAULT_PASSWORD: "NTV360-Passbolt-Poc-2026!"
      DATASOURCES_DEFAULT_DATABASE: passbolt

      ####################################
      # SMTP (Mailpit)
      ####################################
      EMAIL_TRANSPORT_DEFAULT_HOST: mailpit
      EMAIL_TRANSPORT_DEFAULT_PORT: 1025
      EMAIL_TRANSPORT_DEFAULT_TLS: "false"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ""
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ""

      EMAIL_DEFAULT_FROM: passbolt@ntv360.internal
      EMAIL_DEFAULT_FROM_NAME: "Passbolt Development"

    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt

    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]

    ports:
      - "80:80"
      - "443:443"

volumes:
  database_volume:
  gpg_volume:
  jwt_volume: